[package]
name = "gl-rs-cube"
version = "0.1.0"
authors = ["cp_shen <cp_shen@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
